#index:
#    path: /
#    controller: App\Controller\DefaultController::index

item:
    type: rest
    resource: App\Controller\ItemController

items:
    type: rest
    resource: App\Controller\ItemsController
